FROM docker.io/nginx:latest

LABEL org.opencontainers.image.source=https://github.com/apscandy/cab230-react-express-app

LABEL maintainer="n11270179@qut.edu.au"

EXPOSE 80

COPY ./nginx.conf /etc/nginx/nginx.conf

COPY ./dist /var/www/