FROM docker.io/node:20-slim AS build

LABEL org.opencontainers.image.source=https://github.com/apscandy/cab230-react-express-app

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

CMD [ "node", "index.js"]