FROM docker.io/node:22-bullseye-slim AS build

LABEL org.opencontainers.image.source=https://github.com/apscandy/cab230-react-express-app

WORKDIR /app

COPY package*.json ./

# RUN openssl genrsa -out private.pem 4096 && openssl rsa -in private.pem -pubout -out public.pem

RUN npm install

COPY . .

EXPOSE 3000

CMD [ "node", "index.js"]